version: '3.8'

services:
  app:
    build: .
    container_name: node-app
    restart: unless-stopped
    env_file:
      - .env
    command: ["node", "index.js"]
    volumes:
      - /etc/localtime:/etc/localtime:ro

  bot:
    build: .
    container_name: node-bot
    restart: unless-stopped
    env_file:
      - .env
    command: ["/bin/sh", "-c", "cp /shared-data/schoolData.json /app/schoolData.json && node bot.js"]
    depends_on:
      - app
    volumes:
      - shared-data:/shared-data
      - /etc/localtime:/etc/localtime:ro

  file-helper:
    image: busybox
    container_name: file-helper
    volumes:
      - shared-data:/shared-data
    command: ["sh", "-c", "cp /source/schoolData.json /shared-data/schoolData.json"]
    volumes_from:
      - node-bot

volumes:
  shared-data:
