services:
  app:
    build: .
    container_name: node-app
    restart: unless-stopped
    env_file:
      - .env
    command: ["node", "index.js"]
    volumes:
      - /etc/localtime:/etc/localtime:ro

  file-helper:
    image: busybox
    container_name: file-helper
    volumes:
      - ./schoolData.json:/tmp/schoolData.json:ro
      - shared-data:/shared-data
    command: ["sh", "-c", "cp /tmp/schoolData.json /shared-data/schoolData.json"]

  bot:
    build: .
    container_name: node-bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - file-helper
    command:
      - /bin/sh
      - -c
      - |
        while [ ! -f /shared-data/schoolData.json ]; do
          echo "Waiting for schoolData.json..."
          sleep 0.5
        done
        cp /shared-data/schoolData.json /app/schoolData.json
        node bot.js
    volumes:
      - shared-data:/shared-data
      - /etc/localtime:/etc/localtime:ro

volumes:
  shared-data:
